spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
#  ai:
#    google:
#      genai:
#        api-key: ${GEMINI_API_KEY}
#        chat:
#          model: gemini-3.6-flash

  ai:
    openai:
      base-url: https://api.groq.com/openai/v1
      api-key: ${GROQ_API_KEY2}
      chat:
        model: openai/gpt-oss-20b

server:
  port: 8090