spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: interview-service
              uri: lb://INTERVIEW-SERVICE
              predicates:
                - Path=/api/v1/interviews/**

            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/v1/ai/**

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${FRONTEND_URL}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

server:
  port: 8222